# Generated by Django 3.2.15 on 2022-10-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
